name: Matrix Example

on:
  push:
    branches:
    - master

jobs:
  matrix-node:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - run: node --version

  matrix-echo:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        echo: ["hello", "world"]
    steps:
    - run: echo ${{ matrix.echo }}

  matrix-cypress:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.15.0-chrome86-ff82
    strategy:
      matrix:
        spec:
        - cypress/integration/one.spec.js
        - cypress/integration/two.spec.js

    steps:
    - uses: actions/checkout@v2

    - uses: cypress-io/github-action@v2
      with:
        install-command: npm i
        spec: ${{ matrix.spec }}
        working-directory: app
